version: '3.8'

services:
  app:
    build: .
    image: nextjs-docker-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start